apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: lab
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  type: LoadBalancer
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka