apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: lab
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
    - name: prometheus
      port: 9090
      targetPort: prometheus